name: Bug Report
description: File a bug report
title: ":bug:: <ここにタイトルを記入してください>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        以下のフォームに沿ってバグ報告をよろしくお願いいたします!
  - type: checkboxes
    id: directory
    attributes:
      label: どのディレクトリの問題ですか?
      options:
        - label: playtest-gauge-browser
        - label: playtest-gauge-rest
        - label: playtest-gauge-db
        - label: playtest-browser
        - label: playtest-json
        - label: playtest-db
        - label: e2e
        - label: README
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 具体的にどのような問題がありましたか?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        報告いただきありがとうございます!