name: Feature Request
description: New feature or request
title: ":sparkles:: <ここにタイトルを記入してください>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        以下のフォームに沿って機能リクエストをよろしくお願いいたします!
  - type: checkboxes
    id: directory
    attributes:
      label: どのディレクトリについてですか?
      options:
        - label: playtest-gauge-browser
        - label: playtest-gauge-rest
        - label: playtest-gauge-db
        - label: playtest-browser
        - label: playtest-json
        - label: playtest-db
        - label: e2e
        - label: README
    validations:
      required: true
  - type: textarea
    id: what-feature
    attributes:
      label: 具体的にどのような機能ですか?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        報告いただきありがとうございます!