name: playtest-json deploy to sonatype
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: デプロイするバージョン
        default: 1.0-SNAPSHOT

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
   #   - name: Unit test
   #     run: cd playtest-json && mvn test
      - name: Deploy
        run: |
          echo "${{ github.event.inputs.version  }}"
          mvn clean deploy --batch-mode --no-transfer-progress -DperformRelease=true -Dproject.version=${{ github.event.inputs.version }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
