name: deploy to sonatype
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: デプロイするバージョン
        default: 1.0-SNAPSHOT

jobs:
  java-version-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: java --version

