name: deploy to sonatype prd
on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        required: true
        description: デプロイするモジュール
        options:
          - playtest-db
          - playtest-gauge-browser
          - playtest-gauge-db
          - playtest-gauge-rest
          - playtest-json

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Build & Unit Test & Deploy
        run: |
          cd ${{ github.event.inputs.module }} && mvn clean deploy --batch-mode --no-transfer-progress -DperformRelease=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
