name: deploy to sonatype prd
on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        required: true
        description: デプロイするモジュール
        options:
        - playtest-db
        - playtest-gauge-db
        - playtest-browser
        - playtest-gauge-browser
        - playtest-gauge-rest
        - playtest-json

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Gauge install
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install java --version 0.7.15
          gauge version
      - name: run db
        if: github.event.inputs.module == 'playtest-gauge-db'
        run: |
          cd  playtest-gauge-db/docker/db/postgresql/
          docker compose up -d
      - name: Build & Unit Test & Deploy
        run: |
          cd ${{ github.event.inputs.module }} && mvn clean deploy --batch-mode --no-transfer-progress -DperformRelease=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
